### ISSUE TITLE
Adopt a more meaningful VC-JWT specification title

### ISSUE THREAD

**Issue by selfissued** [w3c/vc-jwt#16]
The current spec title is "JSON Web Token".  I propose to change it to the more meaningful "JSON Web Token Representation for Verifiable Credentials".

@OR13 @Sakurann , please review.

**Comment by OR13** [comment]
agree

**Comment by OR13** [comment]
https://github.com/w3c/vc-jwt/pull/20

**Comment by Sakurann** [comment]
agree to change the title, not agreeing with the proposed option, made a PR comment.

**Comment by selfissued** [comment]
Fixed by https://github.com/w3c/vc-jwt/pull/20 .
