### ISSUE TITLE
Write meaningful Abstract

### ISSUE THREAD

**Issue by selfissued** [w3c/vc-jwt#17]
The abstract currently says "This specification does neat stuff."  I propose to use this as a starting point for a meaningful abstract:
> This specification defines a JSON Web Token (JWT) [RFC7519] representation of Verifiable Credentials.

@OR13 @Sakurann please review.

**Comment by OR13** [comment]
https://github.com/w3c/vc-jwt/pull/19

**Comment by selfissued** [comment]
Fixed by https://github.com/w3c/vc-jwt/pull/19
