### ISSUE TITLE
Delete "still" in description of JWT

### ISSUE THREAD

**Issue by selfissued** [w3c/vc-jwt#18]
https://w3c.github.io/vc-jwt/#json-web-token says "JSON Web Token (JWT) [[RFC7519](https://w3c.github.io/vc-jwt/#bib-rfc7519)] is still a widely used means to express claims to be transferred between two parties."  The use of "still" sounds pejorative and doesn't add anything actionable to the spec.  Let's delete "still".

Attn: @OR13 @Sakurann

**Comment by OR13** [comment]
agree

**Comment by OR13** [comment]
https://github.com/w3c/vc-jwt/commit/62c2c858309877cfd0fde7b5805c909de45794e8

I am assuming this is not controversial... but I will revert if requested.

**Comment by Sakurann** [comment]
+1 to both suggestion and the commit

**Comment by selfissued** [comment]
Fixed by https://github.com/w3c/vc-jwt/commit/62c2c858309877cfd0fde7b5805c909de45794e8
