### ISSUE TITLE
Bad website link in Github repo

### ISSUE THREAD

**Issue by peacekeeper** [w3c/vc-jwt#2]
There's a wrong link in the Githup repo. Should be **w3c.github.io/vc-jwt/** instead I think?

---- 
![Screenshot from 2022-07-31 16-36-19](https://user-images.githubusercontent.com/290941/182031467-5e992ad2-56aa-4968-b0cc-5e52fed4726b.png)
----

**Comment by iherman** [comment]
Oops, sorry, my mistake. Settled.
