### ISSUE TITLE
Respec warnings and errors

### ISSUE THREAD

**Issue by OR13** [w3c/vc-jwt#27]
We need to setup the bib and xref properly so vc-jwt can cite vc-data-model properly and we can get rid of all the undefined term warnings.

<img width="1557" alt="Screen Shot 2022-09-16 at 4 55 40 PM" src="https://user-images.githubusercontent.com/8295856/190807069-a9f958e5-a880-4be7-9cc2-4368ad9de192.png">

**Comment by selfissued** [comment]
I don't know this tool set well enough to know how to do this.  Do you, @OR13 ?  Or if not, do you know who might know, @Sakurann ?

**Comment by OR13** [comment]
I fixed this.
