### ISSUE TITLE
Update language to align with v2 resolutions

### ISSUE THREAD

**Issue by OR13** [w3c/vc-jwt#38]
`issuanceDate`, `validFrom`, `validUntil`

**Comment by Sakurann** [comment]
we should agree that iat/exp of VC-JWT are validity of the VC-JWT signature and are different from ValifFrom/ValidUntil that are validity of the data in the Credential https://github.com/w3c/vc-jwt/issues/39#issuecomment-1382640644

**Comment by OR13** [comment]
@Sakurann I agree they are different, I presented on this at TPAC.

Basically:

```
proof.created => iat
issuanceDate => nbf
expirationDate => exp
```

changing the name of the left hand side does not change the mapping:

```
proof.created => iat
validFrom => nbf
validUntil => exp
```

**Comment by Sakurann** [comment]
I agree with
> proof.created <=> iat

I dont with

> validFrom <=> nbf
> validUntil <=> exp

ValidFrom and validUntil should not be mapped to any JWT Claim and used as-is. and exp JWT Claim should be used for the JWS signature validity.

Please see my proposal in issue #4

**Comment by OR13** [comment]
@Sakurann 

`validFrom` ~= `issuanceDate` 
`validUntil ` ~= `expirationDate` 

See 1.1 production rules:

https://w3c.github.io/vc-jwt/#in-addition-to

These are the rules for 1.1... 

We can of course change them or not implement a similar mapping for 2.0.

**Comment by OR13** [comment]
No longer needs, especially when #88 is merged
