### ISSUE TITLE
Should we shorten `verifiable-credential+jwt` to `vc+jwt`?

### ISSUE THREAD

**Issue by OR13** [w3c/vc-jwt#45]
Follows from the conventions for JWT, shorter is better.

**Comment by selfissued** [comment]
The shortening works for me.

**Comment by OR13** [comment]
I think it is a best practice to shorten per the RFC. 


https://www.rfc-editor.org/rfc/rfc7515#section-4.1.10

```
To keep messages compact in common situations, it is RECOMMENDED that
producers omit an "application/" prefix of a media type value in a
"cty" Header Parameter when no other '/' appears in the media type
value.  A recipient using the media type value MUST treat it as if
"application/" were prepended to any "cty" value not containing a
'/'.  For instance, a "cty" value of "example" SHOULD be used to
represent the "application/example" media type, whereas the media
type "application/example;part="1/2"" cannot be shortened to
"example;part="1/2"".
```

**Comment by TallTed** [comment]
I don't quite understand why a JWT best practice (which recommends only omission of the expected most-common media type prefix, `application/`; it does not say anything about otherwise shortening media types) is being cited to justify shortening a media type which may be used anywhere (including but not limited to JWTs).

Rather, I might expect [RFC 6838: Media Type Specifications and Registration Procedures](https://www.rfc-editor.org/rfc/rfc6838) (and those it obsoleted/updated) to be cited … but I don't see any similar recommendation there, so I'm not sure this really *is* a Media Typing best practice.

I'm certain that most [expansions of `vc`](https://www.acronymfinder.com/VC.html) (which do not yet, but should soon, include Verifiable Credential) are not relevant, but I'm also willing to bet that there are at least a few `vc` which might be relevant to `jwt` encoding. This would tend to argue against the shortening.

**Comment by OR13** [comment]
@TallTed I don't understand what you are saying... are suggesting verbose (less ambiguous) names are a best practice for JWTs?

**Comment by dlongley** [comment]
@OR13,

> @TallTed I don't understand what you are saying... are suggesting verbose (less ambiguous) names are a best practice for JWTs?

I don't think so. I think he's saying that a media type is being registered, so the best practices for media types should be followed; best practices for JWTs are not relevant.

**Comment by dlongley** [comment]
> and guidance on media types is more relevant than guidance on JWTs.

When naming a media type, that's what most people would expect, I'd think.

**Comment by OR13** [comment]
Most of the recent media types I have seen use abbreviation.

When registering a media type for use with JWT, I would expect abbreviation.

I think `vc+jwt` is the path forward.

**Comment by selfissued** [comment]
I also agree that `application/vc+jwt` is the more natural naming.  Note that this community typically uses the verbal shorthand "VC" when talking about a Verifiable Credential.  Our media type name might as well do the same.

**Comment by OR13** [comment]
PR is up: https://github.com/w3c/vc-jwt/pull/50

**Comment by TallTed** [comment]
To answer various questions above.... I feel that:

* Advice about minting media types should be followed when minting media types. Advice about shortening the content of JWS (e.g., by omitting `application/` — and *only* `application/` — from the payload's media type when encoding in a JWS `cty` field) is not relevant to minting those media types.

* Media types should be as long and verbose as is necessary (and no more so) for them to be sufficiently unambiguous for their purposes and uses. `application/vc+jwt` *might* be such, but I think there needs to be some reasonable time spent in researching whether there are any other `vc` that this might lead to confusion with.

* An _issue_ should be used to discuss a perceived *possible problem* (which here appears to be "is the `application/verifiable-credential+jwt` media type too long?") and its potential *solutions* ("Should it be shortened to `application/vc+jwt`, to match the W3C short name? Should it remain full-length? Is there a better, different, longer-or-shorter type name?"), until something like consensus is found on the _actual problem and the best solution_, at which point it is appropriate to create a pull request to apply that solution.  An _issue_ should not be titled with a predetermined (proposed) _solution_, which may or may not have consensus support, which is then immediately applied via a PR authored by the issue's author.  I do not think it sufficient that two people agree either that there is a problem, nor that five appear to agree on the single solution proposed for the as-yet unclearly stated "problem" (i.e., what is the impact of having the longer media type when used in JWS? What about the impact of the longer, or shoter, media type in _other_ usage?), for those agreements to be considered group consensus, which is implied by the creation of PR #50.

* @dlongley's [comment](https://github.com/w3c/vc-jwt/pull/50#issuecomment-1426577255) on the prematurely raised PR #50 should be brought here, and the concerns raised there and in my own comments above should be discussed to completion before PR #50 (or subsequent) is merged.

**Comment by dlongley** [comment]
Per @TallTed's request, I'm linking to my [comment](https://github.com/w3c/vc-jwt/pull/50#issuecomment-1426577255) on the other PR, quoted inline here:

> I don't know of any conflicts with the `+jwt` suffix that would cause confusion over this shortening, so it's probably fine from that perspective. It would be good to make usage of `vc` consistent in the various media types we create, however. So if we're going to use `application/vc+jwt` here, we should make sure that `application/verifiable-credential+ld+json` (or whatever we want to use over there) can also be shortened to `application/vc+ld+json` without any trouble.
> 
> So, in general, I'm supportive of this provided that we can be consistent. It's not a deal breaker if we can't be consistent in the end, but I think we should go for consistency over having short names in just one place simply because we're able to shorten it there.

**Comment by TallTed** [comment]
As I said in #50, I do not concur with #50 as resolution to this "issue", which has been closed as it was titled — that is, a foregone conclusion, with which I do not agree.

**Comment by brentzundel** [comment]
Reopening this issue so that raised concerns can have further discussion.

**Comment by brentzundel** [comment]
> Advice about minting media types should be followed when minting media types. Advice about shortening the content of JWS (e.g., by omitting application/ — and only application/ — from the payload's media type when encoding in a JWS cty field) is not relevant to minting those media types.


I believe it is not entirely irrelevant when the media type is intended to be used primarily within a JWS. As long 

> Media types should be as long and verbose as is necessary (and no more so) for them to be sufficiently unambiguous for their purposes and uses. application/vc+jwt might be such, but I think there needs to be some reasonable time spent in researching whether there are any other vc that this might lead to confusion with.

This strikes me as a reasonable concern. I do not know of anyone besides us who are using `vc`, but perhaps others can chime in.

**Comment by TallTed** [comment]
I remain opposed to titling issues with the conclusion sought by the issue creator.

Issues are commonly questions, and should be treated as such. Initial (opening) comments should be conclusion-neutral, though they might include a listing of known "possible solutions" if greater than one, with the commenter's/issue-creator's own preferences not being raised until the next (or later) comment.

Overloading of `VC` is not trivial to check in itself. It may be somewhat easier to check for other uses of `VC` *with `JWT`* (and without "verifiable credentials", "verifiable credential", or "decentralized identity"). Google finds [700,000+ candidate instances of such overload](https://www.google.com/search?q=vc+jwt+-%22verifiable+credential%22+-%22verifiable+credentials%22+-%22decentralized+identity%22). I did notice that users of VisualC/+/++ use `VC`, which may or may not be or become an issue. I imagine that the Google search could be further refined, so the candidate list shortens, but I can't say by how much. 

Knowing that the limited number of three- and four-letter acronyms tends to lead to a great deal of overloading there, and knowing that there are fewer two-letter acronyms than either of those, I think it quite likely there will be some `VC` overloading to be dealt with, even restricting the overloads to uses with `JWT`.

**Comment by brentzundel** [comment]
> I remain opposed to titling issues with the conclusion sought by the issue creator.
> 
> Issues are commonly questions, and should be treated as such. Initial (opening) comments should be conclusion-neutral, though they might include a listing of known "possible solutions" if greater than one, with the commenter's/issue-creator's own preferences not being raised until the next (or later) comment.

While this may be considered best practice, there is no language in the VCWG work mode that indicates this is a requirement for opening issues. That said I have renamed this issue.

> Overloading of `VC` is not trivial to check in itself. It may be somewhat easier to check for other uses of `VC` _with `JWT`_ (and without "verifiable credentials", "verifiable credential", or "decentralized identity"). Google finds [700,000+ candidate instances of such overload](https://www.google.com/search?q=vc+jwt+-%22verifiable+credential%22+-%22verifiable+credentials%22+-%22decentralized+identity%22). I did notice that users of VisualC/+/++ use `VC`, which may or may not be or become an issue. I imagine that the Google search could be further refined, so the candidate list shortens, but I can't say by how much.
> 
> Knowing that the limited number of three- and four-letter acronyms tends to lead to a great deal of overloading there, and knowing that there are fewer two-letter acronyms than either of those, I think it quite likely there will be some `VC` overloading to be dealt with, even restricting the overloads to uses with `JWT`.

Limiting my search to IANA mentions of `vc` I have found the following:

1. `.vc` is the country level domain for St. Vincent and the Grenadines
2. There are a number of RFCs which use `vc` as an acronym (e.g., Virtual Circuit, Video Codec, Virtual Channel), but none of them register a media type that I found.
3. There is a registered JWT claim of `vc` for verifiable credentials.
4. There are no registered application media types that use `vc`. The closest registered media types I found were the `vc1` and `vc2` video codecs.

With this information I am comfortable using `vc` in media types for verifiable credentials-related objects.

**Comment by OR13** [comment]
We merged the PR that did this.
