### ISSUE TITLE
Replace reference to jwt.io with embedded example

### ISSUE THREAD

**Issue by OR13** [w3c/vc-jwt#46]
don't link to jwt.io, instead provide a decoded example inline.

**Comment by David-Chadwick** [comment]
We should also try to be consistent and ensure that all the base64 encoded examples contain the same values as the unencoded examples. For example, the encoded iat in example 9 is "iat": 1675201578, whilst the unencoded value in example 8 is  "iat": 1516239022.

**Comment by OR13** [comment]
I fixed this, closing
