### ISSUE TITLE
JWT Decoding: expirationDate

### ISSUE THREAD

**Issue by vpapanchev** [w3c/vc-jwt#7]
Hi,

I believe there is a small mistake in the [JWT Decoding section](https://www.w3.org/TR/vc-data-model/#jwt-decoding).

It says that the **exp** property of a JWT Credential must be used to set the value of the **expirationDate** of **credentialSubject** of the new JSON object.
If I am not mistaken, it should be used to set the value of the **expirationDate** of the new credential JSON object.

**Comment by selfissued** [comment]
I believe that @vpapanchev 's observation is correct.

**Comment by Sakurann** [comment]
can this be closed as a duplicate of issue #39?

**Comment by OR13** [comment]
closing as dupe
