### ISSUE TITLE
Verification Method type used with VC-JWT

### ISSUE THREAD

**Issue by PhilippGackstatter** [w3c/vc-jwt#83]
Hello,

we are implementing VC-JWT and were wondering what the `type` of a verification method should be when signing a credential according to `VC-JWT`. It seems the spec does not place any restrictions on that, but are there recommendations to maximize interoperability?

Thanks!

**Comment by OR13** [comment]
This is what I tend to use:

- https://jwt.vc/.well-known/did.json

**Comment by OR13** [comment]
I recommend NOT using any key representation that is not trivial to convert to a JWKS.

**Comment by OR13** [comment]
@selfissued @mprorock we should have a controller document to the appending that answers this.

**Comment by OR13** [comment]
The document contains some examples, but in general the 2 concepts are seperate.
